name: libprovn
description: A Dart library for parsing and writing W3C PROV-N (Provenance Notation) and PROV-JSON formats.
version: 1.0.1
homepage: https://github.com/libdbm/libprovn
repository: https://github.com/libdbm/libprovn
issue_tracker: https://github.com/libdbm/libprovn/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  meta: ^1.11.0
  petitparser: ^7.0.1

dev_dependencies:
  test: ^1.25.12
  lints: ^6.0.0
